### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by lsnnt** [nitin30kumar/edu-mail--auto-generator#3]
logs given below
===
<p>E:\edu-mail-auto-generator\bot.py:75: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Firefox(executable_path=r'./webdriver/geckodriver')
E:\edu-mail-auto-generator\bot.py:89: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath('//*[@id="portletContent_u16l1n18"]/div/div[2]/div/a[2]').click()
Traceback (most recent call last):
  File "E:\edu-mail-auto-generator\bot.py", line 1039, in <module>
    main()
  File "E:\edu-mail-auto-generator\bot.py", line 1036, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "E:\edu-mail-auto-generator\bot.py", line 89, in start_bot
    driver.find_element_by_xpath('//*[@id="portletContent_u16l1n18"]/div/div[2]/div/a[2]').click()
  File "C:\Users\Nityanand_Thakur\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 521, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Nityanand_Thakur\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Nityanand_Thakur\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Nityanand_Thakur\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //*[@id="portletContent_u16l1n18"]/div/div[2]/div/a[2]
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:395:5
element.find/</<@chrome://remote/content/marionette/element.js:300:16</p>
===

**Comment by lsnnt** [comment]
i am using ffirefox

**Comment by nitinkumar30** [comment]
Hi @nityanand86876, 
**learn to debug the code with the errors/warnings you're getting.**  

~driver = webdriver.Firefox(executable_path=r'./webdriver/geckodriver')~  - [solution for geckodriver](https://stackoverflow.com/questions/40208051/selenium-using-python-geckodriver-executable-needs-to-be-in-path)

Please use find_element(by=By.XPATH, value=xpath) instead ~driver.find_element_by_xpath('//*[@id="portletContent_u16l1n18"]/div/div[2]/div/a[2]').click()~  

Like above you need to edit the code as Chrome is able to run this script but not Firefox, I guess.  
I'm sure the above will fix your issues. Kindly raise another issue with more details.
